package team.flint.flint.core.mapper;

import team.flint.flint.model.table.FlintLog;

public interface FlintLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    int insert(FlintLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    int insertSelective(FlintLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    FlintLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlintLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flint_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlintLog record);
}