package team.flint.flint.core.mapper;

import team.flint.flint.model.table.Program;
import team.flint.flint.model.table.ProgramWithBLOBs;

import java.util.List;

public interface ProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int insert(ProgramWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int insertSelective(ProgramWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    ProgramWithBLOBs selectByPrimaryKey(Integer programId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProgramWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ProgramWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table program
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Program record);

    List<Program> getProgramList();
}