package team.flint.flint.model.table;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table authority
 */
public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_id
     *
     * @mbg.generated
     */
    private Long authorityId;

    /**
     * Database Column Remarks:
     *   资源ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.resource_id
     *
     * @mbg.generated
     */
    private Integer resourceId;

    /**
     * Database Column Remarks:
     *   员工ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     * Database Column Remarks:
     *   0启用 1禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.is_forbid
     *
     * @mbg.generated
     */
    private Integer isForbid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_id
     *
     * @return the value of authority.authority_id
     *
     * @mbg.generated
     */
    public Long getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_id
     *
     * @param authorityId the value for authority.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(Long authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.resource_id
     *
     * @return the value of authority.resource_id
     *
     * @mbg.generated
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.resource_id
     *
     * @param resourceId the value for authority.resource_id
     *
     * @mbg.generated
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.staff_id
     *
     * @return the value of authority.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.staff_id
     *
     * @param staffId the value for authority.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.is_forbid
     *
     * @return the value of authority.is_forbid
     *
     * @mbg.generated
     */
    public Integer getIsForbid() {
        return isForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.is_forbid
     *
     * @param isForbid the value for authority.is_forbid
     *
     * @mbg.generated
     */
    public void setIsForbid(Integer isForbid) {
        this.isForbid = isForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_time
     *
     * @return the value of authority.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_time
     *
     * @param createTime the value for authority.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.update_time
     *
     * @return the value of authority.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.update_time
     *
     * @param updateTime the value for authority.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}