package team.flint.flint.model.table;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table flint_log
 */
public class FlintLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.log_id
     *
     * @mbg.generated
     */
    private Long logId;

    /**
     * Database Column Remarks:
     *   日志级别 0 ALL，1 TRACE，2 DEBUG，3 INFO，4 WARN，5 ERROR
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.label0
     *
     * @mbg.generated
     */
    private String label0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.label1
     *
     * @mbg.generated
     */
    private String label1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.label2
     *
     * @mbg.generated
     */
    private String label2;

    /**
     * Database Column Remarks:
     *   入参
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.params
     *
     * @mbg.generated
     */
    private String params;

    /**
     * Database Column Remarks:
     *   出参
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.create_df_num
     *
     * @mbg.generated
     */
    private String createDfNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flint_log.create_df
     *
     * @mbg.generated
     */
    private Date createDf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.log_id
     *
     * @return the value of flint_log.log_id
     *
     * @mbg.generated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.log_id
     *
     * @param logId the value for flint_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.level
     *
     * @return the value of flint_log.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.level
     *
     * @param level the value for flint_log.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.label0
     *
     * @return the value of flint_log.label0
     *
     * @mbg.generated
     */
    public String getLabel0() {
        return label0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.label0
     *
     * @param label0 the value for flint_log.label0
     *
     * @mbg.generated
     */
    public void setLabel0(String label0) {
        this.label0 = label0 == null ? null : label0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.label1
     *
     * @return the value of flint_log.label1
     *
     * @mbg.generated
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.label1
     *
     * @param label1 the value for flint_log.label1
     *
     * @mbg.generated
     */
    public void setLabel1(String label1) {
        this.label1 = label1 == null ? null : label1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.label2
     *
     * @return the value of flint_log.label2
     *
     * @mbg.generated
     */
    public String getLabel2() {
        return label2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.label2
     *
     * @param label2 the value for flint_log.label2
     *
     * @mbg.generated
     */
    public void setLabel2(String label2) {
        this.label2 = label2 == null ? null : label2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.params
     *
     * @return the value of flint_log.params
     *
     * @mbg.generated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.params
     *
     * @param params the value for flint_log.params
     *
     * @mbg.generated
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.content
     *
     * @return the value of flint_log.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.content
     *
     * @param content the value for flint_log.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.create_df_num
     *
     * @return the value of flint_log.create_df_num
     *
     * @mbg.generated
     */
    public String getCreateDfNum() {
        return createDfNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.create_df_num
     *
     * @param createDfNum the value for flint_log.create_df_num
     *
     * @mbg.generated
     */
    public void setCreateDfNum(String createDfNum) {
        this.createDfNum = createDfNum == null ? null : createDfNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flint_log.create_df
     *
     * @return the value of flint_log.create_df
     *
     * @mbg.generated
     */
    public Date getCreateDf() {
        return createDf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flint_log.create_df
     *
     * @param createDf the value for flint_log.create_df
     *
     * @mbg.generated
     */
    public void setCreateDf(Date createDf) {
        this.createDf = createDf;
    }
}