package team.flint.flint.model.table;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table program
 */
public class ProgramWithBLOBs extends Program {
    /**
     * Database Column Remarks:
     *   源码地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     * Database Column Remarks:
     *   测试产出内容[{"k":v}]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.dev_output
     *
     * @mbg.generated
     */
    private String devOutput;

    /**
     * Database Column Remarks:
     *   正式产出内容[{"k":v}]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.pro_output
     *
     * @mbg.generated
     */
    private String proOutput;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.source
     *
     * @return the value of program.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.source
     *
     * @param source the value for program.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.dev_output
     *
     * @return the value of program.dev_output
     *
     * @mbg.generated
     */
    public String getDevOutput() {
        return devOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.dev_output
     *
     * @param devOutput the value for program.dev_output
     *
     * @mbg.generated
     */
    public void setDevOutput(String devOutput) {
        this.devOutput = devOutput == null ? null : devOutput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.pro_output
     *
     * @return the value of program.pro_output
     *
     * @mbg.generated
     */
    public String getProOutput() {
        return proOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.pro_output
     *
     * @param proOutput the value for program.pro_output
     *
     * @mbg.generated
     */
    public void setProOutput(String proOutput) {
        this.proOutput = proOutput == null ? null : proOutput.trim();
    }
}