package team.flint.flint.model.table;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table program
 */
public class Program {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.program_id
     *
     * @mbg.generated
     */
    private Integer programId;

    /**
     * Database Column Remarks:
     *   项目名字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   项目描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     * Database Column Remarks:
     *   原型地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.prototype
     *
     * @mbg.generated
     */
    private String prototype;

    /**
     * Database Column Remarks:
     *   预发产出内容[{"k":v}]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.rc_output
     *
     * @mbg.generated
     */
    private String rcOutput;

    /**
     * Database Column Remarks:
     *   0启用 1禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.is_forbid
     *
     * @mbg.generated
     */
    private Integer isForbid;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column program.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.program_id
     *
     * @return the value of program.program_id
     *
     * @mbg.generated
     */
    public Integer getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.program_id
     *
     * @param programId the value for program.program_id
     *
     * @mbg.generated
     */
    public void setProgramId(Integer programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.name
     *
     * @return the value of program.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.name
     *
     * @param name the value for program.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.desc
     *
     * @return the value of program.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.desc
     *
     * @param desc the value for program.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.prototype
     *
     * @return the value of program.prototype
     *
     * @mbg.generated
     */
    public String getPrototype() {
        return prototype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.prototype
     *
     * @param prototype the value for program.prototype
     *
     * @mbg.generated
     */
    public void setPrototype(String prototype) {
        this.prototype = prototype == null ? null : prototype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.rc_output
     *
     * @return the value of program.rc_output
     *
     * @mbg.generated
     */
    public String getRcOutput() {
        return rcOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.rc_output
     *
     * @param rcOutput the value for program.rc_output
     *
     * @mbg.generated
     */
    public void setRcOutput(String rcOutput) {
        this.rcOutput = rcOutput == null ? null : rcOutput.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.is_forbid
     *
     * @return the value of program.is_forbid
     *
     * @mbg.generated
     */
    public Integer getIsForbid() {
        return isForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.is_forbid
     *
     * @param isForbid the value for program.is_forbid
     *
     * @mbg.generated
     */
    public void setIsForbid(Integer isForbid) {
        this.isForbid = isForbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.create_time
     *
     * @return the value of program.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.create_time
     *
     * @param createTime the value for program.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column program.update_time
     *
     * @return the value of program.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column program.update_time
     *
     * @param updateTime the value for program.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}